using Microsoft.CodeAnalysis.CSharp;
using System.Collections.Immutable;
using System.Text;

namespace GitSail.Analyzers;

/// <summary>
/// Emits allocation-light, reflection-free localized message members.
/// </summary>
internal static class LocalizationSourceEmitter
{
    /// <summary>
    /// Emits the complete generated message table.
    /// </summary>
    /// <param name="catalogs">The validated localization catalogs.</param>
    /// <returns>The generated C# source.</returns>
    internal static string Emit(ImmutableArray<LocalizationCatalog> catalogs)
    {
        var orderedCatalogs = catalogs
            .OrderBy(static catalog => catalog.Document.Locale, StringComparer.Ordinal)
            .ToArray();
        var english = orderedCatalogs.Single(static catalog => catalog.Document.Locale == "en");
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace GitSail.Localization.Generated;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Provides strongly typed messages generated from validated locale catalogs.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("internal static class AppMessages");
        builder.AppendLine("{");

        foreach (var englishMessage in english.Document.Messages!.OrderBy(static message => message.Id, StringComparer.Ordinal))
        {
            var translations = orderedCatalogs.ToDictionary(
                static catalog => catalog.Document.Locale!,
                catalog => catalog.Document.Messages!.Single(message => message.Id == englishMessage.Id),
                StringComparer.Ordinal);
            EmitMessage(builder, englishMessage, translations);
        }

        EmitLocaleResolver(builder, orderedCatalogs);
        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>
    /// Converts a semantic message identifier into its generated member name.
    /// </summary>
    /// <param name="messageId">The validated semantic identifier.</param>
    /// <returns>The deterministic Pascal-cased member name.</returns>
    internal static string GetMemberName(string messageId)
    {
        var builder = new StringBuilder(messageId.Length);
        var capitalize = true;
        foreach (var value in messageId)
        {
            if (value is '.' or '-' or '_')
            {
                capitalize = true;
                continue;
            }

            builder.Append(capitalize ? char.ToUpperInvariant(value) : value);
            capitalize = false;
        }

        return builder.ToString();
    }

    private static void EmitMessage(
        StringBuilder builder,
        LocalizationMessageDocument englishMessage,
        Dictionary<string, LocalizationMessageDocument> translations)
    {
        var memberName = GetMemberName(englishMessage.Id!);
        var arguments = (englishMessage.Arguments ?? new Dictionary<string, string>(StringComparer.Ordinal))
            .OrderBy(static argument => argument.Key, StringComparer.Ordinal)
            .ToArray();
        builder.AppendLine("    /// <summary>");
        builder.Append("    /// ").AppendLine(EscapeXml(englishMessage.Description!));
        builder.AppendLine("    /// </summary>");
        foreach (var argument in arguments)
        {
            builder.Append("    /// <param name=\"")
                .Append(argument.Key)
                .Append("\">The ")
                .Append(argument.Key)
                .AppendLine(" value.</param>");
        }

        if (arguments.Length == 0)
        {
            builder.Append("    internal static string ")
                .Append(memberName)
                .Append(" => ")
                .Append(memberName)
                .AppendLine("ForLocale(global::System.Globalization.CultureInfo.CurrentUICulture.Name);");
        }
        else
        {
            builder.Append("    internal static string ").Append(memberName).Append('(');
            AppendArguments(builder, arguments, includeLocale: false);
            builder.Append(") => ").Append(memberName)
                .Append("ForLocale(global::System.Globalization.CultureInfo.CurrentUICulture.Name, ");
            AppendSeparated(builder, arguments.Select(static argument => argument.Key));
            builder.AppendLine(");");
        }

        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.Append("    /// Resolves <c>").Append(englishMessage.Id).AppendLine("</c> for an explicit locale.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <param name=\"localeName\">The requested locale name.</param>");
        foreach (var argument in arguments)
        {
            builder.Append("    /// <param name=\"")
                .Append(argument.Key)
                .Append("\">The ")
                .Append(argument.Key)
                .AppendLine(" value.</param>");
        }

        builder.Append("    internal static string ").Append(memberName).Append("ForLocale(");
        AppendArguments(builder, arguments, includeLocale: true);
        builder.AppendLine(")");
        builder.AppendLine("    {");
        builder.AppendLine("        var locale = ResolveLocale(localeName);");
        EmitPatternSwitch(builder, englishMessage, translations);
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitPatternSwitch(
        StringBuilder builder,
        LocalizationMessageDocument englishMessage,
        Dictionary<string, LocalizationMessageDocument> translations)
    {
        if (englishMessage.Selector is null)
        {
            builder.AppendLine("        return locale switch");
            builder.AppendLine("        {");
            foreach (var translation in translations.OrderBy(static translation => translation.Key, StringComparer.Ordinal))
            {
                builder.Append("            \"").Append(EscapeCSharp(translation.Key)).Append("\" => ")
                    .Append(EmitPattern(translation.Value.Text!)).AppendLine(",");
            }

            builder.Append("            _ => ").Append(EmitPattern(englishMessage.Text!)).AppendLine(",");
            builder.AppendLine("        };");
            return;
        }

        var selector = englishMessage.Selector;
        if (selector.Kind == "plural")
        {
            builder.Append("        var category = global::GitSail.Localization.PluralRules.GetCategory(locale, ")
                .Append(selector.Argument)
                .AppendLine(");");
            builder.AppendLine("        return (locale, category) switch");
            builder.AppendLine("        {");
            foreach (var translation in translations.OrderBy(static translation => translation.Key, StringComparer.Ordinal))
            {
                foreach (var variant in translation.Value.Variants!
                    .Where(static variant => variant.Key != "other")
                    .OrderBy(static variant => variant.Key, StringComparer.Ordinal))
                {
                    builder.Append("            (\"").Append(EscapeCSharp(translation.Key)).Append("\", global::GitSail.Localization.PluralCategory.")
                        .Append(GetMemberName(variant.Key)).Append(") => ")
                        .Append(EmitPattern(variant.Value)).AppendLine(",");
                }

                builder.Append("            (\"").Append(EscapeCSharp(translation.Key)).Append("\", _) => ")
                    .Append(EmitPattern(translation.Value.Variants!["other"])).AppendLine(",");
            }

            builder.Append("            _ => ").Append(EmitPattern(englishMessage.Variants!["other"])).AppendLine(",");
            builder.AppendLine("        };");
            return;
        }

        builder.AppendLine("        return (locale, " + selector.Argument + ") switch");
        builder.AppendLine("        {");
        foreach (var translation in translations.OrderBy(static translation => translation.Key, StringComparer.Ordinal))
        {
            foreach (var variant in translation.Value.Variants!
                .Where(static variant => variant.Key != "other")
                .OrderBy(static variant => variant.Key, StringComparer.Ordinal))
            {
                builder.Append("            (\"").Append(EscapeCSharp(translation.Key)).Append("\", \"")
                    .Append(EscapeCSharp(variant.Key)).Append("\") => ")
                    .Append(EmitPattern(variant.Value)).AppendLine(",");
            }

            builder.Append("            (\"").Append(EscapeCSharp(translation.Key)).Append("\", _) => ")
                .Append(EmitPattern(translation.Value.Variants!["other"])).AppendLine(",");
        }

        builder.Append("            _ => ").Append(EmitPattern(englishMessage.Variants!["other"])).AppendLine(",");
        builder.AppendLine("        };");
    }

    private static string EmitPattern(string pattern)
    {
        _ = LocalizationPatternParser.TryParse(pattern, out var parts, out _);
        if (!parts.Any(static part => part.IsArgument))
        {
            return $"\"{EscapeCSharp(pattern)}\"";
        }

        var builder = new StringBuilder("$\"");
        foreach (var part in parts)
        {
            if (part.IsArgument)
            {
                builder.Append('{').Append(part.Text).Append('}');
            }
            else
            {
                builder.Append(EscapeCSharp(part.Text).Replace("{", "{{").Replace("}", "}}"));
            }
        }

        return builder.Append('"').ToString();
    }

    private static void EmitLocaleResolver(StringBuilder builder, LocalizationCatalog[] catalogs)
    {
        builder.AppendLine("    private static string ResolveLocale(string? localeName)");
        builder.AppendLine("    {");
        builder.AppendLine("        var normalized = global::GitSail.Localization.LocaleNameNormalizer.Normalize(localeName);");
        builder.AppendLine("        return normalized switch");
        builder.AppendLine("        {");
        foreach (var locale in catalogs.Select(static catalog => catalog.Document.Locale!).OrderBy(static locale => locale, StringComparer.Ordinal))
        {
            builder.Append("            \"").Append(EscapeCSharp(locale)).Append("\" => \"")
                .Append(EscapeCSharp(locale)).AppendLine("\",");
        }

        foreach (var locale in catalogs
            .Select(static catalog => catalog.Document.Locale!)
            .Where(static locale => !locale.Contains('-'))
            .OrderBy(static locale => locale, StringComparer.Ordinal))
        {
            builder.Append("            _ when normalized.StartsWith(\"").Append(EscapeCSharp(locale))
                .Append("-\", global::System.StringComparison.Ordinal) => \"")
                .Append(EscapeCSharp(locale)).AppendLine("\",");
        }

        builder.AppendLine("            _ => \"en\",");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
    }

    private static void AppendArguments(
        StringBuilder builder,
        KeyValuePair<string, string>[] arguments,
        bool includeLocale)
    {
        if (includeLocale)
        {
            builder.Append("string? localeName");
            if (arguments.Length > 0)
            {
                builder.Append(", ");
            }
        }

        AppendSeparated(builder, arguments.Select(static argument =>
            $"{GetArgumentType(argument.Value)} {argument.Key}"));
    }

    private static void AppendSeparated(StringBuilder builder, IEnumerable<string> values)
    {
        var separator = string.Empty;
        foreach (var value in values)
        {
            builder.Append(separator).Append(value);
            separator = ", ";
        }
    }

    private static string GetArgumentType(string argumentKind)
        => argumentKind switch
        {
            "integer" => "long",
            "number" => "double",
            _ => "string",
        };

    private static string EscapeCSharp(string value)
        => SymbolDisplay.FormatLiteral(value, quote: false);

    private static string EscapeXml(string value)
        => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
