<Project Sdk="MSTest.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/GitSail/GitSail.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../locales/*.json"
          Link="locales/%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
